### ISSUE TITLE
Kubernetes config with 'exec' resource where exec requires MFA hangs

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#297]
A common way to configure AWS EKS in kube config is
```
user:
  exec:
    apiVersion: client.authentication.k8s.io/v1alpha1
    command: aws-iam-authenticator
    args: [token, -i, infracore-test-1, --cache]
    env:
    - name: AWS_PROFILE
      value: <profile>
```

This will cache and re-use an MFA token if using an account with MFA, but if the token needs to be re-requested Wash hangs, then eventually times out and crashes the terminal.

We need to identify and expose that request for an MFA token when it happens.

----

For completeness, the way the AWS CLI tool sets up kube config is with
```
user:
  exec:
    apiVersion: client.authentication.k8s.io/v1alpha1
    command: aws
    args: [eks get-token --cluster-name <cluster>]
    env:
    - name: AWS_PROFILE
      value: <profile>
```
which doesn't cache the token at all, so it attempts to request an MFA token every time you run kubectl.
