### ISSUE TITLE
Move plugin config to the relevant plugin instead of @ top-level

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#720]
Consider the following `wash.yaml` file
```
external-plugins:
  - script: 'foo'
plugins:
  - 'bar'
foo:
  <foo_config>
bar:
  <bar_config>
```

Having the plugin config @ top-level is a bit confusing. We should change this to something like
```
external-plugins:
  - script: 'foo'
    config: <config stuff>
plugins:
  - name: 'foo'
    config: <config stuff>
```

Note that this would also let us configure an external plugin's name so that it doesn't have to be `<script_without_extension>`. E.g., we could do something like

```
external-plugins:
  - script: 'bar'
    name: 'foo'
    config: <config>
```

And Wash would know that the plugin's name is `foo`.
