### ISSUE TITLE
Invalid kubernetes context produces unhelpful error, exits wash

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#79]
With a `~/.kube/config` including
```
- context:
    cluster: ""
    namespace: webapp
    user: ""
  name: webapp
```
we get
```
WARN[2019-02-23T10:06:28+01:00] invalid configuration: no configuration has been provided
exit status 1
```

Several things should be addressed
- the plugin shouldn't error when a single invalid configuration is found
- failures in a single plugin shouldn't cause wash to exit
- warnings need to provide more context around what caused them
